// react-app/src/components/pages/Categories/CategoryForm/index.jsx
import React, { Fragment } from 'react';

function CategoryForm(props) {
    const category = props.category;
    return (
        <Fragment>
            <div className="form-group">
                <label htmlFor="name">
                    Nome
                </label>
                <input type="text" 
                    className="form-control" 
                    id="name"
                    name="name"
                    maxLength="30"
                    defaultValue={category && category.name ? category.name : ''}
                    placeholder="Informe um nome para a categoria"
                    required />
                <input type="hidden" 
                    name="id" 
                    defaultValue={category && category.id ? category.id : ''} />
            </div>
            <div className="form-group form-check">
                <input type="checkbox" 
                    className="form-check-input"
                    defaultChecked={!category || category.active}
                    id="active"
                    name="active" />
                <label htmlFor="active">
                    Ativo?
                </label>
            </div>
        </Fragment>
    );
}
export default CategoryForm;

// angular-app/src/app/components/pages/category/category-form/category-form.component.ts
import { Component, Input } from '@angular/core';
import { CategoryInterface } from 'src/app/interfaces/category.interface';

@Component({
  selector: 'category-form',
  templateUrl: './category-form.component.html',
  styleUrls: ['./category-form.component.css']
})
export class CategoryFormComponent {

  @Input()
  public category: CategoryInterface = {
    name: '',
    active : true
  };
}

<div class="form-group">
  <label for="name">Nome</label>
  <input type="text" 
         name="category.name" 
         id="name" 
         class="form-control" 
         required 
         placeholder="Informe um nome para a categoria"
         [(ngModel)]="category.name">
</div>
<div class="form-group form-check">
  <input type="checkbox" 
         name="active" 
         id="active"
         class="form-check-input"
         required 
         [(ngModel)]="category.active">
  <label for="active">Ativo?</label>
</div>
