// angular-app/src/app/components/pages/user/user-restore-modal/user-restore-modal.component.ts
import { Component, ViewChild, Output, EventEmitter } from '@angular/core';
import { ModalComponent } from '../../../bootstrap/modal/modal.component';
import { HttpErrorResponse } from '@angular/common/http';
import { UserInterface } from '../../../../interfaces/user.interface';
import { UserHttpService } from '../../../../services/http/user-http.service';

@Component({
  // tslint:disable-next-line:component-selector
  selector: 'user-restore-modal',
  templateUrl: './user-restore-modal.component.html',
  styleUrls: ['./user-restore-modal.component.css']
})
export class UserRestoreModalComponent {

  private user: UserInterface = {
    id: null,
    name: ''
  };

  @ViewChild(ModalComponent)
  private modal: ModalComponent;

  // tslint:disable-next-line:no-output-on-prefix
  @Output()
  onSuccess: EventEmitter<any> = new EventEmitter<any>();

  // tslint:disable-next-line:no-output-on-prefix
  @Output()
  onError: EventEmitter<HttpErrorResponse> = new EventEmitter<HttpErrorResponse>();

  constructor(private userHttp: UserHttpService) { }

  submit() {
    const success = (user) => {
        this.onSuccess.emit(user);
        this.modal.hide();
    };
    const error = (err) => this.onError.emit(err);
    this.userHttp
        .restore(this.user.id)
        .subscribe(success, error);
  }

  showModal(user: UserInterface) {
    this.user.id = user.id;
    this.user.name = user.name;
    this.modal.show();
  }

  hideModal() {
    this.modal.hide();
  }
}

<form (submit)="submit()">  
    <modal>
        <h5 modal-title>
            Restaurar usuário
        </h5>
        <div modal-body>
            Deseja restaurar o usuário {{user?.name}}?
        </div>
        <div modal-footer>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">
                Fechar
            </button>
            &nbsp;
            <button type="submit" class="btn btn-success">
                Restaurar
            </button>
        </div>
    </modal>
</form>

// react-app/src/components/pages/Users/UserRestoreModal/index.jsx
import React, { Fragment } from 'react';

import Modal from '../../../template/Modal';

function ModalFooter(props) {
    return (
        <Fragment>
            <button type="button" 
                className="btn btn-secondary" 
                data-dismiss="modal">
                Fechar
            </button>
            <button type="button" 
                className="btn btn-success" 
                onClick={() => props.handleClick(props.user)}>
                Restaurar
            </button>
        </Fragment>
    );
}

function UserRestoreModal(props) {
    const user = props.user;
    return (
        <Modal
            modalId={props.modalId} 
            title="Restaurar usuário"
            body={`Deseja restaurar o usuário ${user ? user.name : ''}?`}
            footer={
                <ModalFooter 
                    user={user} 
                    handleClick={props.handleClick} />
            }
        />
    );
}
export default UserRestoreModal;
