// react-app/src/components/pages/Users/UserDeleteModal/index.jsx
import React, { Fragment } from 'react';

import Modal from '../../../template/Modal';

function ModalFooter(props) {
    return (
        <Fragment>
            <button type="button" 
                className="btn btn-secondary" 
                data-dismiss="modal">
                Fechar
            </button>
            <button type="button" 
                className="btn btn-danger" 
                onClick={() => props.handleClick(props.user)}>
                Excluir
            </button>
        </Fragment>
    );
}

function UserDeleteModal(props) {
    const user = props.user;
    return (
        <Modal
            modalId={props.modalId} 
            title="Exclusão de usuário"
            body={`Deseja excluir o usuário ${user ? user.name : ''}?`}
            footer={
                <ModalFooter 
                    user={user} 
                    handleClick={props.handleClick} />
            }
        />
    );
}
export default UserDeleteModal;

// angular-app/src/app/components/pages/user/user-delete-modal/user-delete-modal.component.ts
import { Component, ViewChild, Output, EventEmitter } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { ModalComponent } from '../../../bootstrap/modal/modal.component';
import { UserInterface } from 'src/app/interfaces/user.interface';
import { UserHttpService } from 'src/app/services/http/user-http.service';

@Component({
  // tslint:disable-next-line:component-selector
  selector: 'user-delete-modal',
  templateUrl: './user-delete-modal.component.html',
  styleUrls: ['./user-delete-modal.component.css']
})
export class UserDeleteModalComponent {

  private user: UserInterface;

  @ViewChild(ModalComponent)
  private modal: ModalComponent;

  // tslint:disable-next-line:no-output-on-prefix
  @Output()
  onSuccess: EventEmitter<any> = new EventEmitter<any>();

  // tslint:disable-next-line:no-output-on-prefix
  @Output()
  onError: EventEmitter<HttpErrorResponse> = new EventEmitter<HttpErrorResponse>();

  constructor(private userHttp: UserHttpService) { }

  destroy() {
      const success = () => {
          this.onSuccess.emit();
          this.modal.hide();
      };
      const error = (err) => this.onError.emit(err);
      this.userHttp
          .destroy(this.user.id)
          .subscribe(success, error);
  }

  showModal(user: UserInterface) {
      this.user = user;
      this.modal.show();
  }

  hideModal() {
      this.modal.hide();
  }
}

<modal>
    <h5 modal-title>
        Exclusão de usuário
    </h5>
    <div modal-body>
        Deseja excluir o usuário {{user?.name}}?
    </div>
    <div modal-footer>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Fechar
        </button>
        &nbsp;
        <button type="button" class="btn btn-danger" (click)="destroy()">
            Excluir
        </button>
    </div>
</modal>
