// angular-app/src/app/components/bootstrap/modal/modal.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modal',
  templateUrl: './modal.component.html',
  styleUrls: ['./modal.component.css']
})
export class ModalComponent implements OnInit 
{
  constructor() { }

  ngOnInit() { }
}

<div class="modal" tabindex="-1" role="dialog" id="exampleModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
            <ng-content select="[modal-title]"></ng-content>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <ng-content select="[modal-body]"></ng-content>
      </div>
      <div class="modal-footer">
          <ng-content select="[modal-footer]"></ng-content>
      </div>
    </div>
  </div>
</div>

// react-app/src/components/template/Modal/index.jsx
import React from 'react';

function Modal(props) {
    return (
        <div className="modal" tabIndex="-1" role="dialog" id={props.modalId}>
            <div className="modal-dialog" role="document">
                <div className="modal-content">
                    <div className="modal-header">
                        <h5 className="modal-title">
                            {props.title}
                        </h5>
                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div className="modal-body">
                        {props.body}
                    </div>
                    <div className="modal-footer">
                        {props.footer}
                    </div>
                </div>
            </div>
        </div>
    );
}
export default Modal;
