// react-app/src/components/pages/Users/UserForm/index.jsx
import React, { Fragment } from 'react';

function UserForm(props) {
    const user = props.user;
    const editMode = user && user.id;
    return (
        <Fragment>
            <div className="form-group">
                <label htmlFor="name">
                    Nome
                </label>
                <input type="text" 
                    className="form-control" 
                    name="name"
                    required
                    placeholder="Informe um nome para o usuário"
                    onChange={() => props.formDataChanged()}
                    value={user && user.name ? user.name : ''}
                    maxLength="30" />
                <input type="hidden" 
                    name="id" 
                    defaultValue={user && user.id ? user.id : ''} />
            </div>
            <div className="form-group">
                <label htmlFor="email">
                    E-mail
                </label>
                <input type="email" 
                    className="form-control"
                    name="email"
                    required 
                    placeholder="Informe um e-mail para o usuário"
                    onChange={() => props.formDataChanged()}
                    value={user && user.email ? user.email : ''}
                    readOnly={editMode} />
            </div>
            <div className="form-group">
                <label htmlFor="password">
                    Senha
                </label>
                <input type="password"
                    className="form-control"
                    name="password"
                    required
                    placeholder="Informe uma senha para o usuário"
                    onChange={() => props.formDataChanged()} />
            </div>
        </Fragment>
    );
}
export default UserForm;

// angular-app/src/app/components/pages/user/user-form/user-form.component.ts
import { Component, Input } from '@angular/core';
import { UserInterface } from 'src/app/interfaces/user.interface';

@Component({
  selector: 'user-form',
  templateUrl: './user-form.component.html',
  styleUrls: ['./user-form.component.css']
})
export class UserFormComponent {

  @Input()
  user: UserInterface = {
    name: '',
    email: '',
    password: ''
  };

  @Input()
  editMode: boolean = false;
}

<div class="form-group">
  <label for="name">Nome</label>
  <input type="text" 
         name="user.name" 
         class="form-control" 
         required 
         placeholder="Informe um nome para o usuário"
         [(ngModel)]="user.name">
</div>
<div class="form-group">
  <label for="email">E-mail</label>
  <input type="email" 
         name="user.email" 
         class="form-control" 
         required
         [readonly]="editMode" 
         placeholder="Informe um e-mail para o usuário"
         [(ngModel)]="user.email">
</div>
<div class="form-group">
  <label for="password">Senha</label>
  <input type="password" 
         name="user.password" 
         class="form-control" 
         placeholder="Informe uma senha para o usuário"
         required 
         [(ngModel)]="user.password">
</div>
