// angular-app/src/app/components/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
 
  private credentials = {
      email : '',
      password : ''
  }
  
  constructor() { }

  ngOnInit() {}
  
  public mostra()
  {
      console.log(this.credentials);
  }
}

<form class="form-signin">
  <h1 class="h3 mb-3 font-weight-normal">
      Code Shopping - Login
  </h1>
  <label for="email" class="sr-only">
      E-mail
  </label>
  <input type="email" 
         name="credentials.email"
         [(ngModel)]="credentials.email" 
         class="form-control" 
         placeholder="Digite o e-mail" 
         required 
         autofocus>
  <label for="password" class="sr-only">
      Senha
  </label>
  <input type="password" 
         name="credentials.password"
         [(ngModel)]="credentials.password"
         class="form-control" 
         placeholder="Digite sua senha" 
         required>
  <button class="btn btn-lg btn-primary btn-block" type="button" (click)="mostra()">
      Entrar
  </button>
  {{ credentials | json }}
</form>

// react-app/src/components/pages/Users/Login/index.jsx
import React, { Component } from 'react';

import './floating-label.css';

class Login extends Component {
    render() {
        return (
            <form className="form-signin">
                <div className="text-center mb-4">
                    <h1 className="h3 mb-3 font-weight-normal">
                        <i className="fa fa-code"></i> Code Shopping
                    </h1>
                </div>
                <div className="form-label-group">
                    <input type="email" 
                           id="inputEmail" 
                           className="form-control" 
                           placeholder="Informe seu e-mail" 
                           required 
                           autofocus />
                    <label for="inputEmail">
                        Seu e-mail
                    </label>
                </div>
                <div className="form-label-group">
                    <input type="password" 
                           id="inputPassword" 
                           className="form-control" 
                           placeholder="Digite sua senha" 
                           required />
                    <label for="inputPassword">
                        Sua senha
                    </label>
                </div>
                <button className="btn btn-lg btn-primary btn-block" type="submit">
                    <i className="fa fa-sign-in"></i> Acessar
                </button>
            </form>
        );
    }
}
export default Login;
